const tile_size = 16;
const width_in_tiles = 16;
const height_in_tiles = 12;

const GameTile = struct {
    pos: [2]u32,
    tex: [2]u32,
    tex_idx: usize,
};
const GameLevel = struct {
    layers: [3][height_in_tiles][width_in_tiles]GameTile,
};
pub const level: GameLevel = .{
    .layers = .{
        .{
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 2 }, .tex = .{ 8, 8 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 2 }, .tex = .{ 9, 8 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 3 }, .tex = .{ 8, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 3 }, .tex = .{ 9, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
        },
        .{
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 16, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 0 }, .tex = .{ 16, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 0 }, .tex = .{ 16, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 0 }, .tex = .{ 16, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 0 }, .tex = .{ 16, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 0 }, .tex = .{ 17, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 0 }, .tex = .{ 15, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 1 }, .tex = .{ 16, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 1 }, .tex = .{ 16, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 1 }, .tex = .{ 16, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 1 }, .tex = .{ 16, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 1 }, .tex = .{ 16, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 1 }, .tex = .{ 17, 2 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 1 }, .tex = .{ 15, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 2 }, .tex = .{ 16, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 2 }, .tex = .{ 16, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 2 }, .tex = .{ 16, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 2 }, .tex = .{ 16, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 2 }, .tex = .{ 16, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 2 }, .tex = .{ 17, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 2 }, .tex = .{ 15, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 3 }, .tex = .{ 16, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 3 }, .tex = .{ 16, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 3 }, .tex = .{ 16, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 3 }, .tex = .{ 16, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 3 }, .tex = .{ 16, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 3 }, .tex = .{ 17, 4 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 3 }, .tex = .{ 15, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 4 }, .tex = .{ 15, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 4 }, .tex = .{ 16, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 4 }, .tex = .{ 17, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 4 }, .tex = .{ 15, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 4 }, .tex = .{ 15, 8 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
            },
        },
        .{
            .{
                .{ .pos = .{ 0, 0 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 0 }, .tex = .{ 1, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 0 }, .tex = .{ 1, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 0 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 0 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 0 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 0 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 0 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 0 }, .tex = .{ 7, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 0 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 0 }, .tex = .{ 10, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 0 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 0 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 0 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 0 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 0 }, .tex = .{ 13, 10 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 1 }, .tex = .{ 0, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 1 }, .tex = .{ 0, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 1 }, .tex = .{ 1, 0 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 1 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 1 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 1 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 1 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 1 }, .tex = .{ 8, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 1 }, .tex = .{ 7, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 1 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 1 }, .tex = .{ 10, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 1 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 1 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 1 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 1 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 1 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 2 }, .tex = .{ 0, 1 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 2 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 2 }, .tex = .{ 7, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 2 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 2 }, .tex = .{ 10, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 2 }, .tex = .{ 13, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 2 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 2 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 2 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 2 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 3 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 3 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 3 }, .tex = .{ 8, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 3 }, .tex = .{ 7, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 3 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 3 }, .tex = .{ 10, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 3 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 3 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 3 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 3 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 3 }, .tex = .{ 11, 9 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 4 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 4 }, .tex = .{ 7, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 4 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 4 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 4 }, .tex = .{ 10, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 4 }, .tex = .{ 11, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 4 }, .tex = .{ 11, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 4 }, .tex = .{ 11, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 4 }, .tex = .{ 11, 10 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 4 }, .tex = .{ 11, 10 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 5 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 5 }, .tex = .{ 8, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 5 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 5 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 5 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 5 }, .tex = .{ 6, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 5 }, .tex = .{ 8, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 5 }, .tex = .{ 7, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 5 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 6 }, .tex = .{ 6, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 6 }, .tex = .{ 7, 7 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 6 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 7 }, .tex = .{ 11, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 7 }, .tex = .{ 11, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 7 }, .tex = .{ 10, 3 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 8 }, .tex = .{ 11, 5 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 9 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 10 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
            },
            .{
                .{ .pos = .{ 0, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 1, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 2, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 3, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 4, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 5, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 6, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 7, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 8, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 9, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 10, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 11, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 12, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 13, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 14, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
                .{ .pos = .{ 15, 11 }, .tex = .{ 11, 6 }, .tex_idx = 0 },
            },
        },
    },
};
